[package]
name = "paging"
version = "0.1.0"
authors = ["CÃ©sar Belley <cesar.belley@lse.epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bits = { path = "../bits" }